### ISSUE TITLE
Node32Lite Probe ไม่ได้

### ISSUE THREAD

**Issue by mrchoke** [jackrobotics/Arduino_ESP32_SPS30#1]
ผมเพิ่งหัดเล่นซื้อ Node32 Lite จาก Gravitech มาต่อกับ SPS30 ตามตัวอย่าง แล้ว run code มัน probe ไม่ได้
ไม่แน่ใจว่า Node32 คนละ Revision มีอะไรต้องดูเป็นพิเศษไหมครับ

ผมลอง Tx0,Rx0 Tx1,Rx1  แล้วก็ไม่ได้ ผม define ค่า pin แล้วก็ไม่ได้ 

แต่ต่อแบบ I2C ผม get ข้อมูลได้ครับ

![img_9580](https://user-images.githubusercontent.com/3403645/52321897-8373fe00-2a09-11e9-9286-91c7b0bdee83.jpg)

**Comment by jackrobotics** [comment]
ต่อ i2c กับ uart ต้องดูขา 4 SET ของ sensor ด้วยครับ ถ้าใช้ i2c ให้ต่อลง
Gnd  ถ้า uart ให้ลอยไว้ไม่ต้องต่อครับ

**Comment by mrchoke** [comment]
> ต่อ i2c กับ uart ต้องดูขา 4 SET ของ sensor ด้วยครับ ถ้าใช้ i2c ให้ต่อลง Gnd ถ้า uart ให้ลอยไว้ไม่ต้องต่อครับ
> […](#)

ผมใช้แบบ I2C ได้นะครับ แต่ต่อ UART  ตาม blog แล้ว probe ไม่ได้ พยายาม ต่อ Serial1 ก็ไม่ได้เช่นกัน
ลองต่อกับอีกชุดก็มีอาการเดียวกัน เลยสงสัยว่าบอร์ดคนละ revision มันต่างกันมากไหมเท่าที่ดู pin น่าจะเหมือนกัน

**Comment by jackrobotics** [comment]
เอาใหม่นะครับ ตอนใช้ i2c ได้ คือต่อทั้ง 5 สายใช่ไหมครับ คือ VCC ,GND ,SDA
,SCL ,SET แต่การต่อด้วย uart ใช้ 4 เส้น คือ  VCC, GND, TX, RX  ต่อแค่นี้ครับ
----------
*Best Regards,*

*Mr.Sonthaya Boonchan (Jack)*

*Services :* IoT System, Robotics, Automation, Research and Development,
Maker (DIY)

*HONEYCorporation Co.,Ltd.*
Email : sonthaya.b@honey.co.th
Phone : (+66) 0801427711
Website : http://www.honey.co.th

*HONEYLab.*
Office : 846/137 Prachautid 44 Rd., Bangmod, Thrungkru,  Bangkok, Thailand
10140
Email : lab@honey.co.th
Phone : (+66) 0801427711
Website : http://www.honey-lab.com


ในวันที่ พ. 6 ก.พ. 2019 เวลา 14:57 MrChoke <notifications@github.com>
เขียนว่า:

> ต่อ i2c กับ uart ต้องดูขา 4 SET ของ sensor ด้วยครับ ถ้าใช้ i2c ให้ต่อลง
> Gnd ถ้า uart ให้ลอยไว้ไม่ต้องต่อครับ
> … <#m_-6761221610244699499_>
>
> ผมใช้แบบ I2C ได้นะครับ แต่ต่อ UART ตาม blog แล้ว probe ไม่ได้ พยายาม ต่อ
> Serial1 ก็ไม่ได้เช่นกัน
> ลองต่อกับอีกชุดก็มีอาการเดียวกัน เลยสงสัยว่าบอร์ดคนละ revision
> มันต่างกันมากไหมเท่าที่ดู pin น่าจะเหมือนกัน
>

**Comment by mrchoke** [comment]
> เอาใหม่นะครับ ตอนใช้ i2c ได้ คือต่อทั้ง 5 สายใช่ไหมครับ คือ VCC ,GND ,SDA ,SCL ,SET แต่การต่อด้วย uart ใช้ 4 เส้น คือ VCC, GND, TX, RX ต่อแค่นี้ครับ 

อะฮะ ผมต่อตามรูปแนบข้างบนครับ เสียบ pin ตามใน blog เลย 

T_T

**Comment by jackrobotics** [comment]
ลองสลับขา Rx Tx  หรือยังครับ เผื่อสลับกันอยู่
----------
*Best Regards,*

*Mr.Sonthaya Boonchan (Jack)*

*Services :* IoT System, Robotics, Automation, Research and Development,
Maker (DIY)

*HONEYCorporation Co.,Ltd.*
Email : sonthaya.b@honey.co.th
Phone : (+66) 0801427711
Website : http://www.honey.co.th

*HONEYLab.*
Office : 846/137 Prachautid 44 Rd., Bangmod, Thrungkru,  Bangkok, Thailand
10140
Email : lab@honey.co.th
Phone : (+66) 0801427711
Website : http://www.honey-lab.com


ในวันที่ พ. 6 ก.พ. 2019 เวลา 16:30 MrChoke <notifications@github.com>
เขียนว่า:

**Comment by mrchoke** [comment]
> ลองสลับขา Rx Tx หรือยังครับ เผื่อสลับกันอยู่ 

เดี๋ยวจะลองอีกรอบครับ ตอนนี้เอาไปตั้งวัดเล่นอยู่ ถ้าได้ผลยังไงจะมาถามอีกนะครับ 
👍 
ขอบคุณมากๆครับ

MrChoke

---------- *Best Regards,* *Mr.Sonthaya Boonchan (Jack)* *Services :* IoT System, Robotics, Automation, Research and Development, Maker (DIY) *HONEYCorporation Co.,Ltd.* Email : sonthaya.b@honey.co.th Phone : (+66) 0801427711 Website : http://www.honey.co.th *HONEYLab.* Office : 846/137 Prachautid 44 Rd., Bangmod, Thrungkru, Bangkok, Thailand 10140 Email : lab@honey.co.th Phone : (+66) 0801427711 Website : http://www.honey-lab.com ในวันที่ พ. 6 ก.พ. 2019 เวลา 16:30 MrChoke <notifications@github.com> เขียนว่า:

**Comment by mrchoke** [comment]
วันนี้มาลองใหม่ได้เรียบร้อยแล้วครับต่อ uart ง่ายดีไม่เกะกะขอบคุณมากๆครับ 😀
